### ISSUE TITLE
Exception on Lineage OS

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#115]
```
08-20 09:49:47.959 14538-14538/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gms.persistent, PID: 14538
    java.lang.RuntimeException: Unable to create application com.google.android.gms.common.app.GmsApplication: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10119 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.SecurityException: addOnPermissionsChangeListener: Neither user 10119 nor current process has android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS.
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.content.pm.IPackageManager$Stub$Proxy.addOnPermissionsChangeListener(IPackageManager.java:6155)
        at android.app.ApplicationPackageManager.addOnPermissionsChangeListener(ApplicationPackageManager.java:1442)
        at pui.a(:com.google.android.gms@13272034@13.2.72 (090408-206980955):14)
        at com.google.android.gms.common.app.GmsApplication.onCreate(:com.google.android.gms@13272034@13.2.72 (090408-206980955):46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by butterl** [comment]
any idea how to fix this ?

**Comment by alexsegura** [comment]
AFAIK there is [MicroG](https://lineage.microg.org/) for this (emulate Google services on LineageOS). 
But as for the exception above, I think it's more because the `android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS` value doesn't exist on LineageOS. 

Unfortunately, I have no device to test it.

**Comment by butterl** [comment]
only find these related file in AOSP build，  looks need to find the permission defined and rebuild the rom？

```
out/soong/hiddenapi/hiddenapi-flags.csv
290:Landroid/Manifest$permission;->OBSERVE_GRANT_REVOKE_PERMISSIONS:Ljava/lang/String;,greylist-max-o

out/soong/hiddenapi/hiddenapi-stub-flags.txt
290:Landroid/Manifest$permission;->OBSERVE_GRANT_REVOKE_PERMISSIONS:Ljava/lang/String;

out/target/product/generic/system/etc/permissions/privapp-permissions-platform.xml
118:        <permission name="android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS"/>

out/target/product/generic/obj/ETC/privapp-permissions-platform.xml_intermediates/privapp-permissions-platform.xml
118:        <permission name="android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS"/>

```
