### ISSUE TITLE
App crashes on Android 4.4

### ISSUE THREAD

**Issue by alexsegura** [coopcycle/coopcycle-app#185]
It should definitely work on Android 4.4.

Below is the stack trace from Google Play

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2264)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2390)
  at android.app.ActivityThread.access$800 (ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1321)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:5299)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:829)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:645)
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.ClassNotFoundException: 
  at dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:497)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:457)
  at android.app.Instrumentation.newActivity (Instrumentation.java:1061)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2255)
```

**Comment by alexsegura** [comment]
The problem seems to have been introduced when going from `0.13.x` to `0.14.x`

https://github.com/coopcycle/coopcycle-app/compare/v0.13.3...v0.14.1

Maybe when introducing `react-native-ble-plx`?
[Android setup](https://github.com/Polidea/react-native-ble-plx/blob/855e3fe5d84f18c90d84fb3543038567ece4e5cf/README.md#android-example-setup) is not 100% accurate (missing `<uses-sdk/>`)

**Comment by alexsegura** [comment]
Maybe related to #95

**Comment by alexsegura** [comment]
Complete stack trace from emulator

```
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/fr.coopcycle-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.coopcycle-1, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4882)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4485)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/fr.coopcycle-1.apk"],nativeLibraryDirectories=[/data/app-lib/fr.coopcycle-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4867)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4485) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5103) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:525) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method)
```
